function configureDropDownLists(rest, menu) {
  var Thu = [
    "မာလာရှမ်းကောပွဲသေး",
    "မာလာရှမ်းကောပွဲကြီး",
    "ချဉ်ပေါင်ကြော်ထမင်းသုပ် ",
    "မျှစ်ကြော်ထမင်းသုပ်    ",
    "လက်ဖက်ထမင်းသုပ်    ",
    "ငပိထောင်းထမင်းသုပ်  ",
    "ငါးပိရည်ကျိုထမင်းသုပ် ",
    "ငံပြာရည်ကြော်ထမင်းသုပ် ",
    "ကြက်အူချောင်းထမင်းသုပ် ",
    "ပဲပုတ်ထမင်းသုပ် ",
    "ကြက်သားဆီပြန်ဇလုံထမင်းသုပ်  ",
    "ကြက်ရှူးရှဲဇလုံထမင်းသုပ် ",
    "ဘဲဥချဉ်ဇလုံထမင်းသုပ် ",
    "ပုဇွန်ဆီပြန်ဇလုံထမင်းသုပ်  ",
    "ကြက်ဖက်ကဗောင်+ထမင်းဖြူ ",
    "ကြက်ဖတ်ပစ်+ထမင်းဖြူ  ",
    "ပင်လယ်စာကွန့်ထန်    ",
    "ပင်လယ်စာအစုံဗန်း   ",
    "ကြက်ကုန်းဘောင်+ထမင်းဖြူ    ",
    "မြေအိုးထမင်းပေါင်း   ",
    "မြေအိုးမြီးရှည်   ",
    "ကြာဇံကြော် ",
    "ပသျှူးထမင်းကြော် ",
    "ရေညှိထမင်းလိပ် ",
    "မာလာ CP   ",
    "မာလာ hot dog ",
    "နံပြားချဉ်စပ်  ",
    "ကိုရီးယားကြက်စပ်ကြော်  ",
    "Fish Cake ",
    "2xSpicy with topping  ",
    "ဖက်ထုပ်ကြော်    ",
    "အာလူးချောင်းကြော်    ",
    "Bubble Milk Tea    ",
    "Brownsugar Bubble Milk Tea ",
    "Milk Green Tea ",
    "Chocolate Bubble   ",
    "Milk Green Tea ",
    "Rose Milk Tea  ",
    "Boba Fresth Milk ",
    "Strawberry Soda ",
    "Blueberry Soda ",
    "Grape Soda ",
    "Passion Soda   ",
    "Kiwi Soda  ",
    "Orange Soda    ",
    "စတော်ဘယ်ရီသီးဖျော်ရည်   ",
    "ထောပတ်သီးဖျော်ရည် ",
    "နာနတ်သီးဖျော်ရည် ",
    "ဖရဲသီးဖျော်ရည်  ",
  ];
  var Nyein = [
    "Chocalate bubble milk tea (small)",
    "Chocolate bubble milk tea (large)",
    "သင်္ဘောသီးထောင်း",
    "2xspicy ကြက်ပေါင်ပါ",
    "ကြက်အပ်မှိုလိပ်",
    "Green Tea (small)",
    "Green Tea (large)",
    "Taiwan Bubble Milk Tea (small)",
    "Taiwan Bubble Milk Tea (large)",
    "Brown Sugar Bubble Tea (small)",
    "Brown Sugar Bubble Tea (large)",
    "Rose Bubble Milk Tea",
    "Macho Green Tea",
    "Tea Cream",
    "Strawberry Milk Shake",
    "ပိန်းဥ Milk Shake",
    "Chocolate Milk Tea",
    "ဂျယ်လီရေခဲမုန့် ",
    "ဂျယ်လီရေခဲသုပ်",
    "ဖာလူဒါ",
    "ဒူးရင်းမလိုင်",
    "စတော်ဘယ်ရီသီးဖျော်ရည်",
    "Orange Soda",
    "Strawberry Soda",
    "Green Apple Soda",
    "Lychee Soda",
    "Pineapple Soda ",
    "Blue Berry Soda",
    "Blue Hawai Soda",
    "Red Berry Soda",
    "Kiwi Soda",
    "Passion Fruit Soda",
    "Cream Soda",
    "Italion Cream Soda",
    "Water Melon Soda",
    "သရက်သီး Slush ",
    "စတော်ဘယ်ရီသီး Slush",
    "ဖရဲသီး Slush",
    "နာနတ် Slush",
    "ငှက်ပျော် Slush ",
    "ပန်သီးစိမ်း Slush",
    "လိုင်ချီး Slush",
    "Blue Hawai Slush",
    "Blue Berry Slush",
    "Red Berry Slush ",
    "Coffee Float",
    "Sea Salt Coffee Cream",
    "Ice Coffee",
    "ထောပတ်သီးကော်ဖီအနစ်ဖျော်ရည်",
    "Ice Coffee Espresso",
    "Craramal Coffee ",
    "Jaba Chip Coffee",
    "ဆုကော်ဖီ",
    "မေမြို့ ဖရက်",
    "ချဉ်ပေါင်ကြော်ထမင်းသုပ်",
    "မျှစ်ကြော်ထမင်းသုပ်",
    "ငံပြာရည်ကြော်ထမင်းသုပ်",
    "ပုန်းရည်ကြီးထမင်းသုပ်",
    "ငါးငပိရည်ကျိုထမင်းသုပ်",
    "ကြက်ဥချောင်းထမင်းသုပ်",
    "သုံးမျိုးစပ်ထမင်းသုပ် ",
    "လက်ဖက်ထမင်း",
    "ရိုးရိုးထမင်းသုပ်",
    "ခေါက်ဆွဲသုပ်",
    "ထမင်းဖြူ",
    "ဖက်ထုပ်အိုးကပ်",
    "ဖက်ထုပ်ကြော်",
    "မာလာထမင်း",
    "မာလာရှမ်းကော ပွဲသေး",
    "မာလာရှမ်းကော ပွဲကြီး",
    "မာလာဟော့ဒေါ့",
    "အာလူးမာလာ",
    "ပေါင်မုန့်ကြက်ဥကြော်",
    "ဆီချက်ခေါက်ဆွဲ",
    "ရှမ်းခေါက်ဆွဲ",
    "ရွှေတောင်ခေါက်ဆွဲ",
    "ဂဏန်းကော်ပျော့ ကြော်",
    "2xspicy ကြက်ပေါင်ပါ",
    "နံပြားချဉ်စပ်",
    "ရေညှိထမင်းလိပ်",
    "အာလူးချောင်းကြော်(အချို)",
    "အာလူးချောင်းကြော်(အစပ်)",
    "ကိုရီးယားကြက်ကြော်",
    "တရုတ်ထမင်းကြော်(ကြက်)",
    "တရုတ်ထမင်းကြော်(ပုစွန်)",
    "ကိုရီယားအကင်စုံ",
    "ပုစွန်တန်ပူရာ ကြော်",
    "အပ်မှိုတန်ပူရာ ကြော်",
    "ပုဇွန်ချိစ်ကင်",
    "ဘေကွန်အပ်",
    "ကြက်အပ်မှိုလိပ်",
    "ယိုးဒယားဝက်ဂုတ်သားကင်",
    "ကြက်သားပြားကင် ",
    "ယိုးဒယားပဲကြာဇံထောင်း",
    "ယိုးဒယားသင်္ဘောသီးထောင်း",
    "ယမ်ယမ်ချဉ်စပ် ထောင်း",
    "ပြောင်းဖူးထောင်း",
    "အပ်မှိုချဉ်စပ် ထောင်း",
    "မုန့်ဖက်ထောင်း",
    "ဥနီထောင်း",
    "ကြက်ခြေထောက်ထောင်း",
    "ကြက်ခြေထောက်ပေါင်းအချို",
    "ကြက်ခြေထောက်ချဉ်စပ်ပေါင်း",
    "ရေဘဝဲထောင်း",
    "ကွေ့တယို",
  ];

  var Immortal = [
    "Spicy Chicken (Normal)",
    "IM Chicken Sweet (Normal)",
    "Chicken Supreme (Normal)",
    "Chicken Golden Delight (Normal) ",
    "BBQ Chicken (Spicy) (Normal)",
    "Popper Chick Bacon & Cheese (Normal)",
    "Bacon Special (Normal)",
    "Double cheese (Normal)",
    "Pepperoni Cheese (Normal)",
    "Grand Pepperoni (Normal)",
    "Chicken Hawaiian (Normal)",
    "Grilled Chicken & Bacon (Normal)",
    "Seafood Supreme (Normal)",
    "Prawn and Crab Stick (Normal)",
    "Garlic Prawn (Normal)",
    "Rolling Fish Ball (Normal)",
    "Special Spicy Prawns (Normal) ",
    "Cheesy Corn (Normal)",
    "Craft Stick Special (Normal) ",
    "IM Veggie (Normal)",
    "Cheesy Tomato (Normal) ",
    "Durian Special (Normal)",
    "Blueberry Special (Normal) ",
    "Chocolate Special (Normal)",
    "Tuna Special (Normal)",
    "IM Supreme Beef (Normal)",

    "(Family)  Spicy Chicken",
    "(Family) IM Chicken Sweet",
    "(Family) Chicken Supreme",
    "(Family) Chicken Golden Delight ",
    "(Family) BBQ Chicken (Spicy)",
    "(Family) Popper Chick Bacon & Cheese",
    "(Family) Bacon Special",
    "(Family) Double cheese",
    "(Family) Pepperoni Cheese",
    "(Family) Grand Pepperoni",
    "(Family) Chicken Hawaiian",
    "(Family) Grilled Chicken & Bacon",
    "(Family) Seafood Supreme",
    "(Family) Prawn and Crab Stick",
    "(Family) Garlic Prawn",
    "(Family) Rolling Fish Ball",
    "(Family) Special Spicy Prawns ",
    "(Family) Cheesy Corn",
    "(Family) Craft Stick Special ",
    "(Family) IM Veggie",
    "(Family) Cheesy Tomato ",
    "(Family) Durian Special",
    "(Family) Blueberry Special ",
    "(Family) Chocolate Special",
    "(Family) Tuna Special",
    "(Family) IM Supreme Beef",
  ];
  var HighClass = [
    "ပေါင်မုန့်နို့စမ်း",
    "မုန့်ဟင်းခါးအရည်ဖျော်",
    "မုန့်ဟင်းခါးသုပ်",
    "ခေါက်ဆွဲသုပ်",
    "ဆန်ပြားသုပ်",
    "နန်းကြီးသုပ် ",
    "ရှမ်းခေါက်ဆွဲ",
    "လက်ဖက်သုပ်",
    "ဂျင်းသုပ်",
    "ခရမ်းချဉ်သီးသုပ်",
    "သံပုရာသီးသုပ်",
    "ဆေးဘဲဥသုပ်",
    "ကျောက်ပွင့်သုပ်",
    "သံပုရာရည်",
    "ဇီးဖျော်ရည်",
    "သစ်ခွဖျော်ရည်",
    "လိမ္မော်သီးဖျော်ရည်",
    "ပန်းသီးဖျော်ရည်",
    "စပျစ်သီးဖျော်ရည်",
    "ပေါင်မုန့်ရေခဲညှပ်",
    "နို့အေး",
    "နွားနို့",
    "စတော်ဘယ်ရီဖျော်ရည်",
    "ထောပတ်သီးဖျော်ရည်",
    "ဖာလူဒါ",
    "ကြေးအိုးချဉ်စပ်",
    "ကြေးအိုး(ကြက်)",
    "ကြေးအိုးဆီချက်(ကြက်)",
    "ယိုးဒယားထမင်းကြော်(ကြက်)",
    "မလေးရှားထမင်းကြော်(ကြက်)",
    "ကတ်ကြေးကိုက်(ကြက်)",
    "ယိုးဒယားထမင်းကြော်(ဝက်)",
    "မလေးရှားထမင်းကြော်(ဝက်)",
    "ကတ်ကြေးကိုက်(ဝက်)",
    "ခေါက်ဆွဲကြော်(ကြက်)",
    "ကြက်ကီးမားပလာတာ",
    "ကြာဇံကြော်(ကြက်)",
    "ထမင်းကြော်(ကြက်)",
    "ပသျှူးထမင်းကြော်(ကြက်) ",
    "ဆီချက်ခေါက်ဆွဲ(ကြက်)",
    "ကြာဇံကြော်(ဝက်)",
    "ထမင်းကြော်(ဝက်)",
    "ပသျှူးထမင်းကြော်(ဝက်) ",
    "ဆီချက်ခေါက်ဆွဲ(ဝက်)",
    "ချိုချဉ်ကြော်(ကြက်)",
    "ချိုချဉ်ကြော်(၀က်)",
    "ကုန်းဘောင်ကြီးကြော်(၀က်)",
    "ကုန်းဘောင်ကြီးကြော်(ကြက်)",
    "ကြက်အစိမ်းကြော်(ကြက်)",
    "အစိမ်းကြော်(၀က်)",
    "သက်သက်လွှတ်အစိမ်းကြော်",
    "ကန်စွန်းပလိန်း",
    "မုန်ညှင်းပလိန်း",
    "ထမင်းဖြူ",
    "လက်ဖက်ထမင်း",
    "ထမင်းသုပ်",
    "ကြက်ဥမွှေကြော်",
    "ကြက်ဥဟက် ",
    "ကြက်ဆီထမင်း",
    "မက်ဆီကန်လက်ဖက်ရည်",
    "ပဲ ပလာတာ",
    "သကြားပလာတာ",
    "ကြက်ဥပေါင်မုန့်ကြော်",
  ];
  var MiSo = [
    "ရေညှိထမင်းလိပ် ",
    "ရေညှိထမင်းလိပ် (Tuna)",
    "ပဲခေါက်ဆွဲ",
    "ကိုရီးယားကြာဇံကြော် ",
    "ထမင်းပေါင်း(ကိုရီးယားဆော့စ်)",
    "ကိုရီးယားထမင်းသုပ်",
    "တော့ပူကီ",
    "ငါးအူချောင်း",
    "ကြေးအိုး(ကြက်)",
    "ခေါက်ဆွဲပြုတ်",
    "ကန်တုန်ထမင်းကြော်",
    "လက်ဖက်ထမင်း",
    "ပေါင်မုန့်ကြက်ဥကြော်",
    "Burger(chicken)",
    "Burger(Beef)",
    "Tuna Sandwich",
    "Cheese Sandwich",
    "Chicken Sandwich",
    "အာလူးချောင်း",
    "သီးစုံထမင်း ကြော်",
    "ကမ်ချီထမင်း ကြော်",
    "ခေါက်ဆွဲကြော်",
    "စတော်ဘယ်ရီ",
    "သံပုရာရည်",
    "ပျားသံပုရာ",
    "Strawberry Soda",
    "Blueberry Soda",
    "Kiwi Soda",
    "Espresso",
    "Cappuccino",
    "Latte",
    "Mocha",
    "Americano",
    "Hot Milk",
    "Cold Milk",
    "Hot Chocolate",
    "Brew Coffee ",
    "Iced Chocolate",
    "Mike Shake (Any)",
    "Honey Lemon",
    "Blue Hawaii",
    "Hot Coffee",
    "Ice Coffee",
    "Iced Espresso",
    "Iced Cappuccino",
    "Iced Cafe Latte",
    "Iced Mocha",
    "Iced Hazelnut",
    "Toffeenut Latte",
    "Yogurt",
    "Strawberry Yogurt",
    "Banana Yogurt",
    "Blueberry Yogurt",
    "Strawberry Smoothies",
    "Blueberry Smoothies",
    "kiwi Smoothies",
  ];

  var YoeShin = [
    "Espresso (Hot)",
    "Americano (Hot)",
    "Lime Americano (Hot)",
    "Cocoa (Hot)",
    "Peach Coffee (Hot)",
    "Cappuccino (Hot)",
    "Latte (Hot)",
    "Caramel Latte (Hot)",
    "Vanilla Latte (Hot)",
    "Mocha (Hot)",
    "Lemon Tea (Hot)",
    "Green Tea (Hot)",
    "Thai Lemon Tea (Hot)",
    "Espresso (Cold)",
    "Americano (Cold)",
    "Lime Americano (Cold)",
    "Cocoa (Cold)",
    "Peach Coffee (Cold)",
    "Cappuccino (Cold)",
    "Latt (Cold)",
    "Caramel Latte (Cold)",
    "Vanilla Latte (Cold)",
    "Mocha (Cold)",
    "Lemon Tea (Cold)",
    "Green Tea (Cold)",
    "Thai Lemon Tea (Cold)",
    "Strawberry Yogurt Smoothie",
    "Chocolate Smoothie",
    "Yogurt Smoothie",
    "Kiwi Smoothie",
    "Ocean Kiwi Soda",
    "Ocean Rose Soda",
    "Paradise Grape Soda",
    "Paradise Rose Soda",
    "Blueberry Soda",
    "Mixbarries Soda",
    "Lime Soda",
    "Peach Soda",
    "Orange Soda",
    "Cheese Sandwiches ",
    "Chicken Sandwiches",
    "Tuna Sandwiches",
  ];

  var canteen=[
    "လက်ဖက်ထမင်း",
    "ထမင်းသုပ်",
    "မုန့်ဟင်းခါးသုပ်",
    "ရောသုပ် ",
    "ထမင်းပုံစား (အသားတစ်မျိူး+အရံနှစ်မျိူး)",
    "ကြာဇံဟင်းခါး",
    "သင်္ဘောသီးထောင်း",
    "ခေါက်ဆွဲပြုတ်",
    "ဟော့ဒါ့ ",
    "ပသျှူးထမင်းကြော်",
    "ဆီချက်ခေါက်ဆွဲ ",
    "ရှမ်းခေါက်ဆွဲ",
    "ကြက်ဥဟက်",
    "ကြက်ဥမွှေကြော် "
    ];

  switch (rest.value) {

    case "Thu":
      menu.options.length = 0;
      for (i = 0; i < Thu.length; i++) {
        createOption(menu, Thu[i], Thu[i]);
      }
      break;

    case "Nyein":
      menu.options.length = 0;
      for (i = 0; i < Nyein.length; i++) {
        createOption(menu, Nyein[i], Nyein[i]);
      }
      break;

    case "Immortal":
      menu.options.length = 0;
      for (i = 0; i < Immortal.length; i++) {
        createOption(menu, Immortal[i], Immortal[i]);
      }
      break;
    case "HighClass":
      menu.options.length = 0;
      for (i = 0; i < HighClass.length; i++) {
        createOption(menu, HighClass[i], HighClass[i]);
      }
      break;
    case "MiSo":
      menu.options.length = 0;
      for (i = 0; i < MiSo.length; i++) {
        createOption(menu, MiSo[i], MiSo[i]);
      }
      break;
      case "YoeShin":
        menu.options.length = 0;
        for (i = 0; i < YoeShin.length; i++) {
          createOption(menu, YoeShin[i], YoeShin[i]);
        }
        break;
        case "canteen":
          menu.options.length = 0;
          for (i = 0; i < canteen.length; i++) {
            createOption(menu, canteen[i], canteen[i]);
          }
          break;
    default:
      menu.options.length = 0;
      break;
  }
}

function createOption(rest, text, value) {
  var opt = document.createElement("option");
  opt.value = value;
  opt.text = text;
  rest.options.add(opt);
}